// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/Context.tsx": () => import("../components/mockups/Context.tsx"),
  "./components/mockups/Onboard.tsx": () => import("../components/mockups/Onboard.tsx"),
  "./components/mockups/context-logo/SymbolDark.tsx": () => import("../components/mockups/context-logo/SymbolDark.tsx"),
  "./components/mockups/context-logo/WordmarkDark.tsx": () => import("../components/mockups/context-logo/WordmarkDark.tsx"),
  "./components/mockups/context-logo/WordmarkLight.tsx": () => import("../components/mockups/context-logo/WordmarkLight.tsx")
};
