import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';

export function Scene4() {
  const [phase, setPhase] = useState(0);

  useEffect(() => {
    const timers = [
      setTimeout(() => setPhase(1), 500),
      setTimeout(() => setPhase(2), 1500),
      setTimeout(() => setPhase(3), 2000),
      setTimeout(() => setPhase(4), 2500),
      setTimeout(() => setPhase(5), 6500),
    ];
    return () => timers.forEach(t => clearTimeout(t));
  }, []);

  return (
    <motion.div 
      className="absolute inset-0 flex items-center justify-center"
      initial={{ opacity: 0, y: 40 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.95, filter: 'blur(5px)' }}
      transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
    >
      <div className="flex flex-col items-center gap-8 w-full max-w-4xl relative z-10">
        
        <motion.div 
          className="text-center"
          initial={{ opacity: 0, y: -20 }}
          animate={phase >= 1 ? { opacity: 1, y: 0 } : { opacity: 0, y: -20 }}
        >
          <div className="text-[#6366F1] font-mono text-sm tracking-widest uppercase mb-2">Generated</div>
          <h2 className="text-4xl font-medium tracking-tight text-white">Post-mortem ready in 3 seconds.</h2>
        </motion.div>

        <motion.div 
          className="bg-[#0f172a] border border-white/10 rounded-xl p-8 w-full shadow-2xl shadow-black/50"
          initial={{ opacity: 0, y: 60, rotateX: 20 }}
          animate={phase >= 2 ? { opacity: 1, y: 0, rotateX: 0 } : { opacity: 0, y: 60, rotateX: 20 }}
          transition={{ type: 'spring', stiffness: 200, damping: 25 }}
          style={{ perspective: 1000 }}
        >
          <div className="flex items-center justify-between mb-8 pb-6 border-b border-white/5">
            <div>
              <h3 className="text-2xl font-medium text-white mb-1">INC-4092: Payment Service Outage</h3>
              <p className="text-white/50 text-sm font-mono">Resolved • Impact: Critical</p>
            </div>
            <div className="bg-emerald-500/10 text-emerald-400 px-3 py-1 rounded-full text-xs font-mono border border-emerald-500/20">
              Generated by Context AI
            </div>
          </div>

          <div className="grid grid-cols-2 gap-8">
            <div className="flex flex-col gap-6">
              <motion.div initial={{ opacity: 0, x: -10 }} animate={phase >= 3 ? { opacity: 1, x: 0 } : { opacity: 0, x: -10 }}>
                <h4 className="text-sm font-mono text-white/40 mb-2 uppercase">Root Cause</h4>
                <p className="text-white/80 text-sm leading-relaxed">
                  Database connection pool exhaustion caused cascading timeouts across dependent services.
                </p>
              </motion.div>
              <motion.div initial={{ opacity: 0, x: -10 }} animate={phase >= 4 ? { opacity: 1, x: 0 } : { opacity: 0, x: -10 }}>
                <h4 className="text-sm font-mono text-white/40 mb-2 uppercase">Action Items</h4>
                <ul className="text-white/80 text-sm leading-relaxed space-y-2 list-disc pl-4">
                  <li>Increase max db connections</li>
                  <li>Implement circuit breaker in auth</li>
                </ul>
              </motion.div>
            </div>
            
            <div>
              <motion.div initial={{ opacity: 0, x: -10 }} animate={phase >= 3 ? { opacity: 1, x: 0 } : { opacity: 0, x: -10 }}>
                <h4 className="text-sm font-mono text-white/40 mb-4 uppercase">Timeline</h4>
                <div className="space-y-4 relative before:absolute before:inset-0 before:ml-[5px] before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-transparent before:via-white/10 before:to-transparent">
                  <div className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active">
                    <div className="flex items-center justify-center w-3 h-3 rounded-full border border-white/20 bg-[#0f172a] group-[.is-active]:bg-[#6366F1] group-[.is-active]:border-[#6366F1] text-slate-500 shadow shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2 z-10"></div>
                    <div className="w-[calc(100%-2rem)] md:w-[calc(50%-2.5rem)] pl-4 md:pl-0 font-mono text-xs text-white/60">14:02: db exhausted</div>
                  </div>
                  <div className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group">
                    <div className="flex items-center justify-center w-3 h-3 rounded-full border border-white/20 bg-[#0f172a] text-slate-500 shadow shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2 z-10"></div>
                    <div className="w-[calc(100%-2rem)] md:w-[calc(50%-2.5rem)] pr-4 md:pr-0 font-mono text-xs text-white/60 text-right">14:03: auth timeout</div>
                  </div>
                </div>
              </motion.div>
            </div>
          </div>
        </motion.div>
      </div>
    </motion.div>
  );
}